name: ðŸš€ Deploy SAXONARA.com via FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: ðŸŽ‰ Syncing Files
    runs-on: ubuntu-latest

    # AIXÃ’ Ã‰S EL QUE EVITARÃ€ QUE ES SOLAPIN PROCESSOS
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true


    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: ðŸ“‚ FTP Upload
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ./saxonara.com/
        # timeout: 60000 # Un minut de marge per si el servidor va lent

        exclude:
          /saxonara-files/
          .git*
          .git*/**

        # CONFIGURACIÃ“ DE RESILIÃˆNCIA:
        timeout: 900000        # Augmentem a 15 minuts (per si un fitxer gran triga)
        log-level: verbose    # AixÃ² ens dirÃ  exactament quin fitxer fa petar la connexiÃ³
        state-name: .ftp-deploy-sync-state.json # AIXÃ’ Ã‰S VITAL PER A PUBLII
